export const SITE = {
  name: 'European Electric LLC',
  shortName: 'European Electric',
  phone: '+1 (230) 456-1552',
  phoneTel: '+12304561552',
  email: 'info@europeanelectric.com',
  address: '380 Albert St, Melbourne, VIC',
  hours: 'Mon–Fri  8:00 AM – 5:00 PM',
  map: {
    lat: -37.8136,
    lng: 144.9631,
    zoom: 14,
    title: 'European Electric LLC — Melbourne',
    markerTitle: 'European Electric LLC',
    markerAddress: '380 Albert St, Melbourne, VIC',
  },
  theme: {
    primary: '#0078C1',
    dark: '#141417',
    muted: '#5a6470',
    light: '#E8F4FC',
  },
  logos: {
    mark: '/assets/images/logo4.png',
    main: '/assets/images/logo2.jpeg',
    mobile: '/assets/images/logo4.png',
    footer: '/assets/images/logo2.jpeg',
    favicon: '/assets/images/logo4.png',
  },
  social: {},
  cta: {
    primary: 'Get a Quote',
    secondary: 'Request a Free Quote',
  },
};
